title = "Vikramjeet Singh"
base_url = "https://vikramxd.github.io"

compile_sass = true
minify_html = true
generate_feed = true
feed_filename = "atom.xml"
build_search_index = true

taxonomies = [
  {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]
smart_punctuation = true

[extra]
# Sets browser theme color,
# see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
primary_color = "#5100ff"

# If the favicon is GIF or not
animated_favicon = false

# Tera date format (not used in comments!),
# see https://docs.rs/chrono/0.4.31/chrono/format/strftime/index.html
# for all available variables.
date_format = "%d %B %Y"

# URL to issue tracker
issues_url = "https://github.com/vikramxd.github.io/issues"

# URL to website's source code
source_url = "https://github.com/vikramxd.github.io"

[extra.nav]
# Display Atom/RSS feed button in the nav
show_feed = false
# Whether to use icons in the nav
icons = false
# Links used in the nav; any icon from https://icons.getbootstrap.com
# can be used as the icon. The bi- prefix should not be added.
links = [
  {url = "/blog", name = "Blog", icon = "journal-bookmark"},
  {url = "https://drive.google.com/file/d/1Q-saA5sHldwApYBU9NpzTtYWxCda52__/view", name = "Resume", icon = "person"},
  {url = "https://github.com/vikramxD", name = "Github", icon = "github"},
  {url = "https://twitter.com/V_J_S_1", name = "Twitter", icon = "twitter"},
]

[extra.footer]
# "© Title, YEAR" in the footer
show_copyright = true
# "Powered by Zola and Duckquill" in footer
show_powered_by = true

# Based on https://github.com/cassidyjames/cassidyjames.github.io/blob/75cd2a202de7a1026de1ea00a4ef1d5b2675c7ff/_config.yaml#L35-L74
#
# Mastodon-powered commenting.
# Values can be overridden in front-matter, e.g.
# for multi-author blogs or guest posts.
#
# These variables are also used for Mastodon verification,
# the needed rel="me" link is set in the head based on these.
[extra.comments]
# Your Mastodon API host; this should be where you have an account
host = "mastodon.social"
# Used to determine who the original/verified poster is;
# role may be expanded in the future (e.g. for moderation).
user = "vikramxD"
